// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjxrulfcscwkdsrrtjta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqeHJ1bGZjc2N3a2RzcnJ0anRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDEzMzcsImV4cCI6MjA1NzUxNzMzN30.LRbBOPBQGv6sV64vMigReo1SeidOx7P4Lbeb2Qtajc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);